FROM ubuntu:bionic

MAINTAINER "Ben Yanke" <ben@benyanke.com>

WORKDIR /tmp

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    software-properties-common && \
    add-apt-repository ppa:ondrej/php -y

# Common PHP pages across containers
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    zip \
    unzip \
    php7.3-cli \
    php7.3-mysqlnd \
    php7.3-apcu \
    php7.3-memcached \
    php7.3-imap \
    php7.3-pgsql \
    php7.3-intl \
    php7.3-mbstring \
    php7.3-redis \
    php7.3-mongo \
    php7.3-sqlite \
    php7.3-curl \
    php7.3-json \
    php7.3-ssh2 \
    php7.3-gd \
    php7.3-gmp \
    php7.3-xml \
    php7.3-zip \
    php7.3-soap \
    php7.3-bcmath \
    php7.3-dev \
    php7.3-ldap \
    php-pear \
    make \
    wget \
    git \
    curl && apt-get clean && rm -rf /var/lib/apt/lists/*

# Enable Opcache
RUN phpenmod opcache

# Copy configuration
COPY config/opcache.ini $PHP_INI_DIR/conf.d/

CMD ["php", "-a"]
